### ISSUE TITLE
Whats up!

### ISSUE THREAD

**Issue by bsvin33t** [KittuJain/dessertStore#1]
Hey @KittuJain @Smruti27 @purnimachinni @vaishalishetty 
I'm going to add all the features that we had discussed into here. You guys can pick it up and start working on it.

--Vineeth BS

**Comment by bsvin33t** [comment]
@KittuJain @purnimachinni @Smruti27 @vaishalishetty 
If you guys need any technical details, please feel free to reach out to me from here.
I hope we have fun!

**Comment by vaishalishetty** [comment]
Sure vineeth..thanks

**Comment by purnimachinni** [comment]
Hey thx Vineeth for drafting all the user stories here. Currently I am not able to contribute, but soon I would be able to start ..

**Comment by bsvin33t** [comment]
@purnimachinni No problem. Feel free to jump right in as soon as you are comfortable.
